### ISSUE TITLE
Leaving conversations

### ISSUE THREAD

**Issue by UdoZa** [WoltLab/com.woltlab.wcf.conversation#128]
Not sure whether this is an error or I'm having troubles understanding it :-)

If a user manually leaves a conversation (via conversation list), hideConversation in wcf1_conversation_to_user is set to 2 and leftAt remains at 0. However, the Conversation class documentation states for leftAt: "timestamp at which the user left the conversation or `0` if they did not leave the conversation". 

Using the ConversationEditor function removeParticipant($userID), which BTW is called by ConversationAction, in a plugin results in an unchanged hideConversation (0 instead of 2) and an update of leftAt to the actual time. Additionally, lastMeassageID is set to an existing messageID instead of null. 

Problem with the later: the user is actually removed (from the perspective of other participants), but the conversation is not hidden in his conversation list and the conversation will not be deleted, when the last participant leaves the conversation.

On this occasion: Conversation class contains "const STATE_LEFT/*4DEAD*/ = 2;"
Is 4DEAD just for fun or is it a cryptic hint for developers?

**Comment by dtdesign** [comment]
There are two different features that are mutual exclusive:

1. The user leaves the conversation at their own will.
  The conversation is removed from their list and can no longer be accessed. `leftAt` does not matter here and it's value is ignored in this case.
2. The user is removed from the conversation by another user.
  Unlike the conversation system in previous versions, users can still access all messages that are visible while they were a part of the conversation. At the same time they are prevented from writing new messages and reading new ones. `leftAt` is the upper boundary for messages to display, `hideConversation` does not apply, because the conversation is still "there".

There is also the companion value `joinedAt` which is used to restrict the visible messages to users that have been added later. When set to `0`, users can see all messages.

In regards to the constant `STATE_LEFT/*4DEAD*/`, this is a reference to the video game "Left 4 Dead". Congratulations, you've found an easter egg ;)

**Comment by UdoZa** [comment]
Ok, thanks, that makes sense.
